outfile:save.o print.o add.o main.o
	cc save.o print.o add.o main.o -o outfile
save.o:save.c
	cc -c save.c -o save.o
print.o:print.c
	cc -c print.c -o print.o
add.o:add.c
	cc -c add.c -o add.o
main.o:main.c
	cc -c main.c -o main.o

