outfile:main.o print.o add_end.o
	cc main.o print.o add_end.o -o outfile
main.o:main.c
	cc -c main.c -o main.o
print.o:print.c
	cc -c print.c -o print.o
add_end.o:add_end.c
	cc -c add_end.c -o add_end.o
