outfile:main.o print.o add.o header.o
	cc main.c print.c add.c header.c -o outfile
header.o:header.c
	cc -c header.c -o header.o
main.o:main.c
	cc -c main.c -o main.o
print.o:print.c
	cc -c print.c -o print.o
add.o:add.c
	cc -c add.c -o add.o


